[transform]
    [transform.test]
        parseColumns = [0,3,4]
        parseDataStartIndex = 1
        parseDataEndIndex = -1
        #fileSplitChar = "" # Split or regex config must be
        fileRegexStr = "[^?!(\\s)]+"
        outputSplitChar = "|"

[load]
    [load.test]
        db = "oracle"
        userName = "username"
        password = "password"
        tnsName = "tnsName"
        loadControlFile = """
                            LOAD DATA
                            INFILE 'workspace/files_parsed/sample_txt/test.parsed'
                            BADFILE 'workspace/files_parsed/sample_txt/test.bad'
                            DISCARDFILE 'workspace/files_parsed/sample_txt/test.dsc'
                            APPEND INTO TABLE SCHEMA_NAME.TABLE_NAME
                            Fields terminated by "|" Optionally enclosed by '"'
                            (
                            DATA_DATE DATE "YYYY-MM-DD HH24:MI" NULLIF (DATA_DATE="NULL"),
                            COLUMN1,
                            COLUMN2
                            )
                        """