[transform]
    [transform.test]
        parseColumns = [0,3,4]
        parseDataStartIndex = 1
        parseDataEndIndex = -1
        fileSplitChar = ""
        fileRegexStr = "[^?!(\\s)]+"
        outputSplitChar = "|"

[load]
    [load.test]
        db = "oracle"
        loadControlFile = """
                            LOAD DATA
                            INFILE 'workspace/files_parsed/sample_txt/test.parsed'
                            BADFILE 'workspace/files_parsed/sample_txt/test.bad'
                            DISCARDFILE 'workspace/files_parsed/sample_txt/test.dsc'
                            APPEND INTO TABLE NORTHI_PARSER_SETTINGS.TEST
                            Fields terminated by "|" Optionally enclosed by '"'
                            (
                            DATA_DATE DATE "YYYY-MM-DD HH24:MI" NULLIF (DATA_DATE="NULL"),
                            COLUMN1,
                            COLUMN2
                            )
                        """